In [13]:
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [31]:
df = pd.read_excel("zomato_data.xlsx")

In [32]:
df.head()

,Order ID,Order Amount (INR),Delivery Time (mins),Order Date,Rating,Number of Items,Delivery Distance (km),Delivery Agent ID,Order Status,Payment Method,...,average_cost_for_two,price_range,highlights,aggregate_rating,votes,photo_count,opentable_support,delivery,state,area
0,1,1930,32,2023-04-30,4.6,9,9.200017,995,Cancelled,Debit Card,...,200,1,"['Credit Card', 'Delivery', 'Takeaway Availabl...",0.0,3,0,0.0,0,Kerala,38863
1,2,371,84,2023-01-06,2.7,1,8.175074,941,Cancelled,UPI,...,1000,3,"['Cash', 'Takeaway Available', 'Breakfast', 'N...",3.6,32,30,0.0,1,Uttar Pradesh,240928
2,3,1389,82,2024-02-18,3.9,5,13.280443,469,Delivered,Debit Card,...,1300,3,"['Cash', 'Debit Card', 'Credit Card', 'Indoor ...",4.4,174,429,0.0,0,Tamil Nadu,130058
3,4,329,50,2023-07-06,1.9,1,11.892893,329,In-Transit,UPI,...,400,1,"['Delivery', 'No Alcohol Available', 'Lunch', ...",3.5,33,48,0.0,0,Delhi,1484
4,5,400,19,2024-06-21,3.4,4,2.570476,172,Cancelled,Credit Card,...,4000,4,"['Cash', 'Dinner', 'Credit Card', 'Lunch', 'Ou...",4.1,112,134,0.0,0,Rajasthan,342239

In [33]:
# Q1. How many total rows and columns are there in the dataset?
df.shape

(12079, 33)

In [34]:
#Q2. What are the names of all the columns in the dataset?
df.columns.tolist()

['Order ID',
 'Order Amount (INR)',
 'Delivery Time (mins)',
 'Order Date',
 'Rating',
 'Number of Items',
 'Delivery Distance (km)',
 'Delivery Agent ID',
 'Order Status',
 'Payment Method',
 'Tip Amount (INR)',
 'Promo Code Applied',
 'Has Free Delivery',
 'res_id',
 'name',
 'type',
 'address',
 'city',
 'locality',
 'latitude',
 'longitude',
 'cuisines',
 'timings',
 'average_cost_for_two',
 'price_range',
 'highlights',
 'aggregate_rating',
 'votes',
 'photo_count',
 'opentable_support',
 'delivery',
 'state',
 'area']

In [35]:
#Q3. What is the data type of each column?
df.dtypes

Order ID                           int64
Order Amount (INR)                 int64
Delivery Time (mins)               int64
Order Date                datetime64[us]
Rating                           float64
Number of Items                    int64
Delivery Distance (km)           float64
Delivery Agent ID                  int64
Order Status                         str
Payment Method                       str
Tip Amount (INR)                   int64
Promo Code Applied                   str
Has Free Delivery                    str
res_id                             int64
name                                 str
type                                 str
address                              str
city                                 str
locality                             str
latitude                         float64
longitude                        float64
cuisines                             str
timings                              str
average_cost_for_two               int64
price_range                        int64
highlights                           str
aggregate_rating                 float64
votes                              int64
photo_count                        int64
opentable_support                float64
delivery                           int64
state                                str
area                               int64
dtype: object

In [36]:
df.select_dtypes(include=['number']).columns
df.select_dtypes(include=['object','category']).columns

/var/folders/dq/q7st889528v76ffzrt2fk2_m0000gn/T/ipykernel_2790/15109061.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=['object','category']).columns

Index(['Order Status', 'Payment Method', 'Promo Code Applied',
       'Has Free Delivery', 'name', 'type', 'address', 'city', 'locality',
       'cuisines', 'timings', 'highlights', 'state'],
      dtype='str')

In [37]:
#Q5. How many missing values are there in each column?
df.duplicated().sum()

np.int64(212)

In [40]:
#Q6. Are there any duplicate rows in the dataset? If yes, how many?
df.duplicated().sum()

np.int64(212)

In [44]:
#Q7. Find the mean, minimum, maximum, and standard deviation of the numerical columns.
df.select_dtypes(include=['number']).agg(['mean','min','max','std'])

,Order ID,Order Amount (INR),Delivery Time (mins),Rating,Number of Items,Delivery Distance (km),Delivery Agent ID,Tip Amount (INR),res_id,latitude,longitude,average_cost_for_two,price_range,aggregate_rating,votes,photo_count,opentable_support,delivery,area
mean,5018.228165,1579.123355,49.578359,3.004330,5.016392,7.653219,546.783012,99.022104,1.275457e+07,21.314166,76.409870,565.568673,1.755774,3.230044,342.867953,265.261611,0.0,0.352264,187558.538372
min,1.000000,150.000000,10.000000,1.000000,1.000000,0.500953,100.000000,0.000000,8.900000e+01,0.000000,0.000000,0.000000,1.000000,0.000000,-18.000000,0.000000,0.0,0.000000,114.000000
max,10000.000000,2999.000000,89.000000,5.000000,9.000000,14.999011,998.000000,199.000000,1.915932e+07,34.084125,91.829984,7500.000000,4.000000,4.900000,42539.000000,16595.000000,0.0,1.000000,342239.000000
std,2883.136265,825.658629,23.196654,1.160856,2.593551,4.207720,260.996003,57.890396,8.276056e+06,6.566635,10.281059,585.135007,0.877094,1.346596,966.653612,883.439879,0.0,0.477696,106274.175728

In [ ]:
df.columns['']

AttributeError: 'DataFrame' object has no attribute 'dtype'